PartyProductMvc/Controllers/AssignPartyController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using PartyProductMvc.Models;

namespace PartyProductMvc.Controllers
{
    public class AssignPartyController : Controller
    {
        private DbService db = new DbService();
        // GET: AssignPart
        public ActionResult AssignPartyList()
        {
            if (Session["Id"] != null)
            {
                return View(db.AssignParties.Include(e => e.Party).Include(x => x.Product).ToList());
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
            
        }

        public ActionResult AssignPartyAddEdit()
        {
            var party = db.Parties;
            var product = db.Products;
            ViewBag.partyList = party;
            ViewBag.productList = product;
            AssignParty ap = new AssignParty()
            {
                AssignPartyId = 0
            };
            return View(ap);
        }

        public ActionResult SaveAssign(AssignParty assignParty)
        {
            if (!ModelState.IsValid)
                return HttpNotFound();
            if (assignParty.AssignPartyId == 0)
            {
                int partyId = assignParty.PartyId;
                int productId = assignParty.ProductId;
                var party = db.Parties.Single(e => e.PartyId == partyId);
                var product = db.Products.Single(e => e.ProductId == productId);
                db.AssignParties.Add(new AssignParty() { Party = party, Product = product });
            }
            else
            {
                var assignFromDb = db.AssignParties.FirstOrDefault(e => e.AssignPartyId == assignParty.AssignPartyId);
                if (assignFromDb == null)
                    return HttpNotFound();

                var partyId = assignParty.PartyId;
                var productId = assignParty.ProductId;
                var party = db.Parties.Single(e => e.PartyId == partyId);
                var product = db.Products.Single(e => e.ProductId == productId);

                assignFromDb.Party = party;
                assignFromDb.Product = product;
            }
           

            db.SaveChanges();
            return RedirectToAction("AssignPartyList");
        }
        public ActionResult Edit(int? id)
        {
           
            if (id == null)
                return HttpNotFound();

            var assignPartyFromDb = db.AssignParties.First(e => e.AssignPartyId == id);
            if (assignPartyFromDb == null)
                return HttpNotFound();
            
            var party = db.Parties;
            var product = db.Products;
            ViewBag.partyList = party;
            ViewBag.productList = product;
            return View("AssignPartyAddEdit",assignPartyFromDb);
        }
        public ActionResult Delete(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var assignPartyFromDb = db.AssignParties.First(e => e.AssignPartyId == id);
            if (assignPartyFromDb == null)
                return HttpNotFound();
            db.AssignParties.Remove(assignPartyFromDb);
            db.SaveChanges();
            return RedirectToAction("AssignPartyList");
        }
    }
}

PartyProductMvc/Controllers/ProductController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PartyProductMvc.Models;

namespace PartyProductMvc.Controllers
{
    public class ProductController : Controller
    {
        private DbService db = new DbService();
        // GET: Product
        public ActionResult ProductList()
        {
            if (Session["Id"] != null)
            {
                var data = db.Products.ToList();
                return View("ProductList", data);

            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public ActionResult ProductAddEdit()
        {
            return View(new Product { ProductId = 0 });
        }

        public ActionResult SaveProduct(Product product)
        {
            if (!ModelState.IsValid)
                return View("ProductAddEdit", product);

            if (product.ProductId == 0)
            {
                db.Products.Add(product);
            }
            else
            {
                var productFromDb = db.Products.FirstOrDefault(e => e.ProductId == product.ProductId);
                if (productFromDb == null)
                    return HttpNotFound();

                productFromDb.ProductName = product.ProductName;
            }

            db.SaveChanges();
            return RedirectToAction("ProductList");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var productFromDb = db.Products.FirstOrDefault(e => e.ProductId == id);
            if (productFromDb == null)
                return HttpNotFound();

            return View("ProductAddEdit", productFromDb);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var productFromDb = db.Products.FirstOrDefault(e => e.ProductId == id);
            if (productFromDb == null)
                return HttpNotFound();
            db.Products.Remove(productFromDb);
            db.SaveChanges();
            return RedirectToAction("ProductList");
        }
    }
}

PartyProductMvc/Controllers/ProductRateController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PartyProductMvc.Models;

namespace PartyProductMvc.Controllers
{
    public class ProductRateController : Controller
    {
        private DbService db = new DbService();
        // GET: ProductRate
        public ActionResult ProductRateList()
        {
            if (Session["Id"] != null)
            {
                
            return View(db.ProductRates.Include(x => x.ProductName).ToList());
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public ActionResult ProductRateAddEdit()
        {
            var products = db.Products.ToList();
            ViewBag.product = products;
            return View(new ProductRate(){Id = 0, DateOfRate = DateTime.Now});
        }

        public ActionResult SaveProductRate(ProductRate productRate)
        {
            if (!ModelState.IsValid)
                return HttpNotFound();

            if (productRate.Id == 0)
            {
                var productId = Convert.ToInt32(productRate.ProductName.ProductName);
                var product = db.Products.Single(e => e.ProductId == productId);

                ProductRate pr = new ProductRate()
                {
                    Rate = productRate.Rate,
                    DateOfRate = productRate.DateOfRate,
                    ProductName = product
                };
                db.ProductRates.Add(pr);
            }
            else
            {
                var assignPartyFromDb = db.ProductRates.FirstOrDefault(e => e.Id == productRate.Id);
                if (assignPartyFromDb == null)
                    return HttpNotFound();
                var prid = Convert.ToInt32(productRate.ProductName.ProductName);
                var product = db.Products.Single(e => e.ProductId == prid);
                assignPartyFromDb.ProductName = product;
                assignPartyFromDb.Rate = productRate.Rate;
                assignPartyFromDb.DateOfRate = productRate.DateOfRate;
            }
                
            db.SaveChanges();
            return RedirectToAction("ProductRateList");
        }

        public ActionResult Edit(int? id)
        {

            if (id == null)
                return HttpNotFound();

            var productRateFromDb = db.ProductRates.First(e => e.Id == id);
            if (productRateFromDb == null)
                return HttpNotFound();

            var product = db.Products;
            
            ViewBag.product = product;
            return View("ProductRateAddEdit", productRateFromDb);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var productRateFromDb = db.ProductRates.First(e => e.Id == id);
            if (productRateFromDb == null)
                return HttpNotFound();
            db.ProductRates.Remove(productRateFromDb);
            db.SaveChanges();
            return RedirectToAction("ProductRateList");
        }
    }
}

PartyProductMvc/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Party Product @ViewBag.Title </title>
    <link rel="stylesheet" href="https://cdn.datatables.net/1.13.7/css/jquery.dataTables.css" />
  
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>

    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Party", "PartyList", "Party")</li>
                    <li>@Html.ActionLink("Products", "ProductList", "Product")</li>
                    <li>@Html.ActionLink("Assign Party", "AssignPartyList", "AssignParty")</li>
                    <li>@Html.ActionLink("Product Rate", "ProductRateList", "ProductRate")</li>
                    <li>@Html.ActionLink("Invoice", "InvoiceAdd", "Invoice")</li>
                    <li id="logoutbtn">@Html.ActionLink("Logout","Index","Home")</li>
                </ul>
            </div>

        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    <script src="https://cdn.datatables.net/1.13.7/js/jquery.dataTables.js"></script>
    <script>
        // Access session data on the client side
        var sessionValue = '@Session["Id"]';

        // Now, you can use sessionValue in your JavaScript code
        if (sessionValue.length == 0) {
            document.getElementById("logoutbtn").style.display = "none";
        } else {
            document.getElementById("logoutbtn").style.display = "block";
        }
    </script>
    @RenderSection("scripts", required: false)


</body>
</html>