PartyProductMvc/Models/Party.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;


namespace PartyProductMvc.Models
{
    public class Party
    {
        [Key]
        public int PartyId { get; set; }

        [Required(ErrorMessage = "Party Name is required..")]
        public string PartyName { get; set; }

    }
}

PartyProductMvc/Controllers/PartyController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Data.Entity.Infrastructure.Interception;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using PartyProductMvc.Models;

namespace PartyProductMvc.Controllers
{
    public class PartyController : Controller
    {
        private DbService db = new DbService();
        // GET: Party
        public ActionResult PartyList()
        {
            if (Session["Id"] != null)
            {
            var data = db.Parties.ToList();
            return View("PartyList",data);
                
            }
            else
            {
                return RedirectToAction("Login", "User");
            }
        }

        public ActionResult PartyAddEdit()
        {
            return View(new Party{PartyId = 0});
        }

        public ActionResult SaveParty(Party party)
        {
            if (!ModelState.IsValid)
                return View("PartyAddEdit", party);

            if (party.PartyId == 0)
            {
                db.Parties.Add(party);
            }
            else
            {
                var partyFromDb = db.Parties.FirstOrDefault(e => e.PartyId == party.PartyId);
                if (partyFromDb == null)
                    return HttpNotFound();

                partyFromDb.PartyName = party.PartyName;
            }

            db.SaveChanges();
            return RedirectToAction("PartyList");
        }

        public ActionResult Edit(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var party = db.Parties.FirstOrDefault(e => e.PartyId == id);
            if (party == null)
                return HttpNotFound();

            return View("PartyAddEdit", party);
        }

        public ActionResult Delete(int? id)
        {
            if (id == null)
                return HttpNotFound();

            var party = db.Parties.FirstOrDefault(e => e.PartyId == id);
            if (party == null)
                return HttpNotFound();

            db.Parties.Remove(party);
            db.SaveChanges();
            return RedirectToAction("PartyList");
        }
    }
}

PartyProductMvc/Views/Party/PartyAddEdit.cshtml
@model PartyProductMvc.Models.Party

@{
    ViewBag.Title = "PartyAddEdit";
}

<h2>PartyAddEdit</h2>


@using (Html.BeginForm("SaveParty","Party")) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Party</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.PartyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PartyName, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PartyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                @Html.HiddenFor(i => i.PartyId)
                <input type="submit" value="Create" class="btn btn-default"/>
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "PartyList")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

PartyProductMvc/Views/Party/PartyList.cshtml
@model IEnumerable<PartyProductMvc.Models.Party>

@{
    ViewBag.Title = "PartyList";
}

<h2>PartyList</h2>

<p>
    @Html.ActionLink("Add New Party", "PartyAddEdit")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.PartyId)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.PartyName)
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.PartyId)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.PartyName)
        </td>
        <td>
            @Html.ActionLink("Edit", "Edit", new { id = item.PartyId }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.PartyId })
        </td>
    </tr>
}

</table>