PartyProductMvc/Models/Invoice.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Linq;
using System.Web;

namespace PartyProductMvc.Models
{
    public class Invoice
    {
        public int Id { get; set; }

        public int PartyId { get; set; }

        public int ProductId { get; set; }

        [Required]
        [DisplayName("Current Rate")]
        public int CurrentRate { get; set; }

        [Required]
        [DisplayName("Quantity")]
        public int Quantity { get; set; }

        public Party Party { get; set; }

        public Product Product { get; set; }
    }
}

PartyProductMvc/Controllers/InvoiceController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Helpers;
using System.Web.Mvc;
using System.Xml.Linq;
using PartyProductMvc.Models;

namespace PartyProductMvc.Controllers
{
    public class InvoiceController : Controller
    {
        private DbService db = new DbService();

        public ActionResult GetInvoice()
        {
            var invoice = db.Invoices.Include(x=>x.Party).Include(x => x.Product);
            
            return Json(new {data = invoice}, JsonRequestBehavior.AllowGet);
        }
        public JsonResult GetProductList(int partyId)
        {
            var productList = db.AssignParties.Include(x => x.Product).Include(x => x.Party).Where(x => x.Party.PartyId == partyId).Select(p => p.Product);
            return Json(productList, JsonRequestBehavior.AllowGet);
        }

        public JsonResult GetProductRate(int productId)
        {
            var productRate = db.ProductRates.Include(a => a.ProductName)
                .Where(x => x.ProductName.ProductId == productId).Select(b => b.Rate);
            return Json(productRate, JsonRequestBehavior.AllowGet);
        }
        // GET: Invoice
        public ActionResult InvoiceAdd()
        {
            if (Session["Id"] != null)
            {
                var party = db.Parties.ToList();
                ViewBag.partyList = party;

                var total = db.Invoices.Sum(x => (int?)x.CurrentRate * (int?)x.Quantity) ?? 0;
                ViewBag.GrandTotal = total;
                return View();
            }
            else
            {
                return RedirectToAction("Login","User");
            }
            
        }

        public ActionResult SaveInvoice(Invoice invoice)
        {
            if (!ModelState.IsValid)
                return HttpNotFound();

            int productId = invoice.ProductId;
            int partyId = invoice.PartyId;
            var product = db.Products.Single(e => e.ProductId == productId);
            var party = db.Parties.Single(e => e.PartyId == partyId);
            db.Invoices.Add(new Invoice()
            {
                ProductId = productId, PartyId = partyId, CurrentRate = invoice.CurrentRate,Quantity = invoice.Quantity
            });

            db.SaveChanges();
            
            return RedirectToAction("InvoiceAdd");
        }

        public ActionResult DeleteInvoice()
        {
            if (!ModelState.IsValid)
                return HttpNotFound();
            var invoices = db.Invoices.ToList();
            foreach (var record in invoices)
            {
                db.Invoices.Remove(record);
            }

            db.SaveChanges();
            return RedirectToAction("InvoiceAdd");
        }
    }
}

PartyProductMvc/Views/Invoice/InvoiceAdd.cshtml
@model PartyProductMvc.Models.Invoice

@{
    ViewBag.Title = "InvoiceAdd";
}

<h2>InvoiceAdd</h2>


@using (Html.BeginForm("SaveInvoice", "Invoice"))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Invoice</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })

        <div class="form-group">
            @Html.LabelFor(model => model.Party.PartyName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.PartyId, new SelectList(ViewBag.partyList, "PartyId", "PartyName"), "Select Party", new { id = "partyDropdown" })
                @Html.ValidationMessageFor(model => model.Party.PartyName, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Product.ProductName, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownListFor(m => m.ProductId, new SelectList(""), "Select Product")
                @Html.ValidationMessageFor(model => model.Product.ProductName, "", new { @class = "text-danger" })
            </div>
        </div>


        <div class="form-group">
            @Html.LabelFor(model => model.CurrentRate, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.CurrentRate, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.CurrentRate, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Quantity, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Quantity, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Quantity, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Add To Invoice" class="btn btn-success" />
            </div>
        </div>
    </div>

    <div class="container">
        <div id="dataTable_wrapper"></div>
        <table id="dataTable" class="table table-bordered table-striped">
            <thead>
                <tr>
                    <th>Id</th>
                    <th>Party</th>
                    <th>Product</th>
                    <th>Rate Of Product</th>
                    <th>Quantity</th>
                    <th>Total</th>
                </tr>
            </thead>
            <tbody>
                <tr>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                    <td></td>
                </tr>
            </tbody>

        </table>
    </div>
    <div class="container">
        <div>
            <label class=" col-md-offset-10 col-md-10">Grand Total: @ViewBag.GrandTotal</label>
        </div>
    </div>



}

@using (Html.BeginForm("DeleteInvoice", "Invoice"))
{
    @Html.AntiForgeryToken()
    <div class="container">
        <div class="col-md-offset-10 col-md-10">
            <input type="submit" value="Close Invoice" class="btn btn-danger"/>
        </div>
    </div>
}
    @section Scripts {
        @Scripts.Render("~/bundles/jqueryval")
        <script>
            $(document).ready(function () {
                $("#partyDropdown").change(function () {
                    $.get("/Invoice/GetProductList", { partyId: $("#partyDropdown").val() }, function (data) {
                        $("#ProductId").empty();
                        $('#ProductId').append("<option value='" + 0 + "'>" + "Select Product" + "</option>")
                        for (let i = 0; i < data.length; i++) {
                            $('#ProductId').append("<option value='" + data[i].ProductId + "'>" + data[i].ProductName + "</option>")
                        }
                    })
                    $("#Product_ProductName").change(function () {
                        $.get("/Invoice/GetProductRate", { productId: $("#ProductId").val() }, function (data) {
                            $("#CurrentRate").val(data[data.length - 1])
                        })
                    })
                })
                let table = new DataTable('#dataTable', {
                    ajax: {
                        "url": "/Invoice/GetInvoice",
                        "type": "GET",
                        "datatype": "json"
                    },
                    columns: [
                        { "data": "Id" },
                        { "data": "Party.PartyName" },
                        { "data": "Product.ProductName" },
                        { "data": "CurrentRate" },
                        { "data": "Quantity" },
                        {
                            "data": null,
                            render: function (data) {
                                var total = data.Quantity * data.CurrentRate;
                                return total.toFixed(2);
                            }
                        }]
                });
            })
        </script>

    }